version: '3.1'

services:
  working-calendar:
    image: henrymorgan2/working-calendar:1.0.0
    container_name: working-calendar_container
    restart: always
    depends_on:
        - database
    environment:
        DATABASE_URL: "jdbc:postgresql://database:5432/working-calendar"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "8080:8080"

  database:
    image: postgres:15.4
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: working-calendar
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ./docker/pgdata

  pgadmin:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/pgadmin